export const PRODUCT_FIELDS = Object.freeze({
	THUMBNAIL: "thumbnail",
	NAME: "name",
	DESCRIPTION: "description",
	PRICE: "price",
	TAGS: "tags",
	QUANTITY_IN_CART: "quantityInCart",
	QUANTITY_SELECTOR: "quantitySelector",
});

export const PRODUCT_VIEWS = {
	grid: [
		PRODUCT_FIELDS.THUMBNAIL,
		PRODUCT_FIELDS.NAME,
		PRODUCT_FIELDS.PRICE,
		PRODUCT_FIELDS.QUANTITY_IN_CART,
	],
	detail: [
		PRODUCT_FIELDS.THUMBNAIL,
		PRODUCT_FIELDS.NAME,
		PRODUCT_FIELDS.DESCRIPTION,
		PRODUCT_FIELDS.TAGS,
		PRODUCT_FIELDS.PRICE,
		PRODUCT_FIELDS.QUANTITY_IN_CART,
		PRODUCT_FIELDS.QUANTITY_SELECTOR,
	],
};