export const PRODUCT_CATEGORIES = Object.freeze({
	ALL: "all",
	APPAREL: "apparel",
	BAG: "bag",
	ELECTRONICS: "electronics",
	FOOD: "food",
	KITCHENWARE: "kitchenware",
	PLUSH: "plush",
	STATIONERY: "stationery",
	MISCELLANEOUS: "miscellaneous",
});

// alphabetical order
export const PRODUCT_CATEGORY_LIST = [
	PRODUCT_CATEGORIES.ALL,
	PRODUCT_CATEGORIES.APPAREL,
	PRODUCT_CATEGORIES.BAG,
	PRODUCT_CATEGORIES.ELECTRONICS,
	PRODUCT_CATEGORIES.FOOD,
	PRODUCT_CATEGORIES.KITCHENWARE,
	PRODUCT_CATEGORIES.PLUSH,
	PRODUCT_CATEGORIES.STATIONERY,
	PRODUCT_CATEGORIES.MISCELLANEOUS,
];
