export const PRODUCT_FIELDS = Object.freeze({
	THUMBNAIL: "thumbnail",
	NAME: "name",
	DESCRIPTION: "description",
	PRICE: "price",
	TAGS: "tags",
});

export const PRODUCT_VIEWS = {
	grid: [
		PRODUCT_FIELDS.THUMBNAIL,
		PRODUCT_FIELDS.NAME,
		PRODUCT_FIELDS.PRICE,
	],
	detail: [
		PRODUCT_FIELDS.THUMBNAIL,
		PRODUCT_FIELDS.NAME,
		PRODUCT_FIELDS.DESCRIPTION,
		PRODUCT_FIELDS.TAGS,
		PRODUCT_FIELDS.PRICE,
	],
};